#!/usr/bin/env bash
# This script reads /etc/passwd and displays username, user ID, and home directory using a while loop
while IFS=: read -r username _ uid _ _ home _
do
	echo "$username:$uid:$home"
done < /etc/passwd
