#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, ordered from most to least frequent
sed -E 's/^([0-9.]+) .* HTTP\/[0-9.]+" ([0-9]+) .*$/\1 \2/' apache-access.log | sort | uniq -c | sort -rn
